version: "3.9"
services:
  api:
    build:
        context: ./DockerSwitch.RestApi
        dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
  svc:
    build:
        context: ./DockerSwitch.KafkaClient
        dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:80"
